### ISSUE TITLE
Crash during startup introduced by commit ba88dc085281403faebe0972dbc0d1f9d19d9f67

### ISSUE THREAD

**Issue by cbackas42** [migueldeicaza/SwiftGodot#744]
**Describe the bug**
Godot crashes during startup with an assert:
Failed to retrieve non-existent singleton 'ClassDB'.
[0;90m   at: get_singleton_object (core/config/engine.cpp:308)[0m
SwiftGodot/ClassDB.swift:29: Fatal error: Unexpectedly found nil while unwrapping an Optional value

Offending stack trace:
In this stack, frame 22 contains the change from the offending commit "_ = type.classInitializer"

```
* thread #1, queue = 'com.apple.main-thread', stop reason = Fatal error: Unexpectedly found nil while unwrapping an Optional value
    frame #0: 0x00000001a4dbb0dc libswiftCore.dylib`_swift_runtime_on_report
    frame #1: 0x00000001a4ea1c38 libswiftCore.dylib`_swift_stdlib_reportFatalErrorInFile + 208
    frame #2: 0x00000001a4ed28a0 libswiftCore.dylib`_assertionFailure(_:_:file:line:flags:) + 364
  * frame #3: 0x00000001249d5578 SwiftGodot`closure #1(ptr=0x7d8d55bf0) in static ClassDB.shared.getter at ClassDB.swift:29:76
    frame #5: 0x00000001249d5388 SwiftGodot`static ClassDB.shared.getter() at ClassDB.swift:28:16
    frame #6: 0x00000001249d7ce4 SwiftGodot`closure #1 in closure #1 in closure #1 in static ClassDB.classExists(pArgs=0x16fdf3920, _result=false) at ClassDB.swift:139:72
    frame #9: 0x00000001249d7b7c SwiftGodot`closure #1 in closure #1 in static ClassDB.classExists(pArgs=0x16fdf3920, _result=false) at ClassDB.swift:138:23
    frame #12: 0x00000001249d7a54 SwiftGodot`closure #1 in static ClassDB.classExists(pArg0=0x16fdf3a48, _result=false) at ClassDB.swift:137:13
    frame #15: 0x00000001249d7980 SwiftGodot`static ClassDB.classExists(class=(content = 33714051216)) at ClassDB.swift:136:9
    frame #16: 0x00000001141fa8d0 FMODSwiftEditor`closure #1() in variable initialization expression of static FMODServer._initializeClass at -9a74bf.@__swiftmacro_15FMODSwiftCommon10FMODServer5GodotfMm_.swift:8:5
    frame #17: 0x00000001141fa810 FMODSwiftEditor`one-time initialization function for _initializeClass() at -9a74bf.@__swiftmacro_15FMODSwiftCommon10FMODServer5GodotfMm_.swift:6:45
    frame #18: 0x000000010aa694dc libdispatch.dylib`_dispatch_client_callout + 16
    frame #19: 0x000000010aa4fa10 libdispatch.dylib`_dispatch_once_callout + 160
    frame #20: 0x00000001141fa800 FMODSwiftEditor`FMODServer._initializeClass.unsafeMutableAddressor() at -9a74bf.@__swiftmacro_15FMODSwiftCommon10FMODServer5GodotfMm_.swift:6:20
    frame #21: 0x00000001141fa7ac FMODSwiftEditor`static FMODServer.classInitializer.getter() at -9a74bf.@__swiftmacro_15FMODSwiftCommon10FMODServer5GodotfMm_.swift:3:12
    frame #22: 0x00000001241688bc SwiftGodot`register<SwiftGodot.Object>(name=(content = 33714051216), parent=(content = 33722564544), type=@thick SwiftGodot.Object.Type) at Wrapped.swift:442:14
    frame #23: 0x000000012416ac78 SwiftGodot`register<SwiftGodot.Object>(type=@thick SwiftGodot.Object.Type) at Wrapped.swift:503:5
    frame #24: 0x0000000114208790 FMODSwiftEditor`registerTypes(types=1 value) at FMODSwift.swift:72:3
    frame #25: 0x0000000114208be0 FMODSwiftEditor`fmodCommonSetupScene(level=servers) at FMODSwift.swift:122:2
    frame #26: 0x0000000114171758 FMODSwiftEditor`fmodEditorSetupScene(level=servers) at FMODSwift.swift:36:2
    frame #29: 0x0000000124172d10 SwiftGodot`extension_initialize(userData=0x7d8965510, l=.GDEXTENSION_INITIALIZATION_SERVERS) at EntryPoint.swift:122:5
    frame #31: 0x0000000104ba5dd0 Godot`GDExtensionManager::initialize_extensions(GDExtension::InitializationLevel) + 92
    frame #32: 0x00000001008755b8 Godot`Main::setup2(bool) + 2420
    frame #33: 0x000000010086efec Godot`Main::setup(char const*, int, char**, bool) + 96336
    frame #34: 0x00000001007f76d8 Godot`OS_MacOS_NSApp::start_main() + 52
    frame #35: 0x0000000191bef484 CoreFoundation`__CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 148
    frame #36: 0x0000000191c53f34 CoreFoundation`___CFXRegistrationPost_block_invoke + 92
    frame #37: 0x0000000191c53e78 CoreFoundation`_CFXRegistrationPost + 436
    frame #38: 0x0000000191bcdf9c CoreFoundation`_CFXNotificationPost + 740
    frame #39: 0x0000000193def308 Foundation`-[NSNotificationCenter postNotificationName:object:userInfo:] + 88
    frame #40: 0x0000000196006e74 AppKit`-[NSApplication _postDidFinishNotification] + 284
    frame #41: 0x0000000196006c24 AppKit`-[NSApplication _sendFinishLaunchingNotification] + 172
    frame #42: 0x000000019657e56c AppKit`-[NSApplication(NSAppleEventHandling) _handleAEOpenEvent:] + 488
    frame #43: 0x0000000196581d70 AppKit`-[NSApplication(NSAppleEventHandling) _handleCoreEvent:withReplyEvent:] + 488
    frame #44: 0x0000000193d3c728 Foundation`-[NSAppleEventManager dispatchRawAppleEvent:withRawReply:handlerRefCon:] + 316
    frame #45: 0x00000001933fb688 Foundation`_NSAppleEventManagerGenericHandler + 80
    frame #46: 0x0000000199e140f4 AE`___lldb_unnamed_symbol872 + 1600
    frame #47: 0x0000000199e13a34 AE`___lldb_unnamed_symbol871 + 44
    frame #48: 0x0000000199e0d0e8 AE`aeProcessAppleEvent + 484
    frame #49: 0x000000019e6097b8 HIToolbox`AEProcessAppleEvent + 68
    frame #50: 0x00000001960020f8 AppKit`_DPSNextEvent + 1296
    frame #51: 0x0000000196acff44 AppKit`-[NSApplication(NSEventRouting) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 688
    frame #52: 0x0000000196acfc50 AppKit`-[NSApplication(NSEventRouting) nextEventMatchingMask:untilDate:inMode:dequeue:] + 72
    frame #53: 0x0000000195ffa780 AppKit`-[NSApplication run] + 368
    frame #54: 0x000000010083532c Godot`main + 908
    frame #55: 0x0000000191791d54 dyld`start + 7184


```**To Reproduce**
Steps to reproduce the behavior:
1. Use SwiftGodot ba88dc085281403faebe0972dbc0d1f9d19d9f67 or later
2. Try to register a class in your initHook during the "servers" Initialiazation phase

**Expected behavior**
No crash

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS Tahoe 26.1, and Fedora Linux 43
 - Godot: 4.5.1
